// data/words.js
// Word list for /wordle. Plain common 5-letter English words — the daily
// word is picked deterministically from this list based on the date, so
// everyone gets the same word on the same day (like the original Wordle).
module.exports = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
  'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'awake', 'award',
  'aware', 'badly', 'baker', 'bases', 'basic', 'basis', 'beach', 'began', 'begin', 'being',
  'below', 'bench', 'birth', 'black', 'blame', 'blank', 'blast', 'blind', 'block', 'blood',
  'board', 'boost', 'booth', 'bound', 'brain', 'brand', 'bread', 'break', 'breed', 'brief',
  'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'calm', 'candy',
  'canon', 'carry', 'catch', 'cause', 'chain', 'chair', 'chart', 'chase', 'cheap', 'check',
  'chest', 'chief', 'child', 'chose', 'civil', 'claim', 'class', 'clean', 'clear', 'click',
  'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court', 'cover',
  'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd', 'crown', 'crude', 'curve',
  'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut', 'delay', 'depth', 'diner',
  'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream', 'dress', 'drill', 'drink',
  'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite', 'empty', 'enemy',
  'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra',
  'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fight', 'final', 'first', 'flash',
  'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum', 'found', 'frame',
  'fresh', 'front', 'fruit', 'fully', 'funny', 'giant', 'given', 'glass', 'globe', 'going',
  'grace', 'grade', 'grand', 'grant', 'grass', 'great', 'green', 'greet', 'gross', 'group',
  'grown', 'guard', 'guess', 'guide', 'happy', 'harsh', 'heart', 'heavy', 'hence', 'horse',
  'hotel', 'house', 'human', 'ideal', 'image', 'index', 'inner', 'input', 'issue', 'joint',
  'judge', 'juice', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'lease', 'least', 'leave', 'legal', 'level', 'light', 'limit', 'lodge', 'logic', 'loose',
  'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'match', 'maybe',
  'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model', 'money',
  'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'never', 'newly',
  'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'order',
  'other', 'ought', 'outer', 'owner', 'panel', 'paper', 'party', 'peace', 'phase', 'phone',
  'photo', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point',
  'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof',
  'proud', 'prove', 'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range', 'rapid',
  'ratio', 'reach', 'ready', 'refer', 'relax', 'reply', 'right', 'rival', 'river', 'roast',
  'robot', 'rough', 'round', 'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score',
  'sense', 'serve', 'seven', 'shade', 'shake', 'shall', 'shape', 'share', 'sharp', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sight',
  'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile',
  'smoke', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak', 'speed',
  'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand', 'start',
  'state', 'steam', 'steel', 'stick', 'still', 'stock', 'stone', 'stood', 'store', 'storm',
  'story', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet',
  'table', 'taken', 'taste', 'teach', 'thank', 'theme', 'there', 'these', 'thick', 'thing',
  'think', 'third', 'those', 'three', 'threw', 'throw', 'tight', 'timer', 'title', 'today',
  'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade', 'train', 'treat', 'trend',
  'trial', 'tribe', 'trick', 'tried', 'tries', 'truck', 'truly', 'trust', 'truth', 'twice',
  'under', 'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid',
  'value', 'video', 'virus', 'visit', 'vital', 'voice', 'waste', 'watch', 'water', 'weigh',
  'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'world', 'worry',
  'worse', 'worst', 'worth', 'would', 'wound', 'write', 'wrong', 'wrote', 'yield', 'young',
];
